frr defaults traditional
hostname r3
!
router bgp 65003
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 10.5.13.1 remote-as 65001
 neighbor 10.5.13.1 timers connect 5
 neighbor 10.5.34.2 remote-as 64512
 neighbor 10.5.34.2 timers connect 5
!
