frr defaults traditional
hostname r4
!
router bgp 64512
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 neighbor 10.5.24.1 remote-as 65002
 neighbor 10.5.24.1 timers connect 5
 neighbor 10.5.34.1 remote-as 65003
 neighbor 10.5.34.1 timers connect 5
 !
 address-family ipv4 unicast
  network 10.50.100.0/24
 exit-address-family
!
