# renew_before_expiry = 30 days
version = 3.0.0
archive_dir = /work/acme/certbot/config/archive/test.local
cert = /work/acme/certbot/config/live/test.local/cert.pem
privkey = /work/acme/certbot/config/live/test.local/privkey.pem
chain = /work/acme/certbot/config/live/test.local/chain.pem
fullchain = /work/acme/certbot/config/live/test.local/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = <account-id-omitted>
authenticator = standalone
http01_port = 5002
server = https://pebble:14000/dir
