bootstrap.servers=<CLUSTER_BOOTSTRAP_ENDPOINT>
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<APP_CONSUMER_API_KEY>" password="<APP_CONSUMER_API_SECRET>";
