bootstrap.servers=<CLUSTER_BOOTSTRAP_ENDPOINT>
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<API_KEY>" password="<API_SECRET>";
schema.registry.url=<SCHEMA_REGISTRY_ENDPOINT>
basic.auth.credentials.source=USER_INFO
schema.registry.basic.auth.user.info=<SR_API_KEY>:<SR_API_SECRET>
