bootstrap.servers=<CLUSTER_BOOTSTRAP_ENDPOINT>
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=<API_KEY>
sasl.password=<API_SECRET>
schema.registry.url=<SCHEMA_REGISTRY_ENDPOINT>
schema.registry.username=<SR_API_KEY>
schema.registry.password=<SR_API_SECRET>
