frr defaults traditional
hostname onp
!
router bgp 65000
 bgp router-id 192.168.10.1
 no bgp ebgp-requires-policy
 neighbor 169.254.10.1 remote-as 64512
 neighbor 169.254.10.1 timers connect 5
 !
 address-family ipv4 unicast
  network 192.168.10.0/24
  network 192.168.20.0/24
  aggregate-address 192.168.0.0/16 summary-only
 exit-address-family
!
