frr defaults traditional
hostname tgw
!
router bgp 64512
 bgp router-id 10.70.255.2
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 169.254.10.2 remote-as 65000
 neighbor 169.254.10.2 timers connect 5
 !
 address-family ipv4 unicast
  network 10.70.0.0/16
 exit-address-family
!
