"""
Minimal Secrets Manager rotation Lambda for a generic (non-database) app
secret. Implements AWS's required 4-step rotation lifecycle
(createSecret / setSecret / testSecret / finishSecret).

No real secret material is embedded in this file. The new value is
generated by calling secretsmanager:GetRandomPassword -- this function
never invents, stores, or logs a credential itself, and never prints the
secret value to CloudWatch Logs.

Reference (AWS's own rotation function contract):
https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_lambda-function-overview.html

This is deliberately the SIMPLEST possible shape: there is no downstream
system to push the new value to (contrast a real DB-credential rotation,
which would ALTER the DB user's password in setSecret). The app always
reads whichever version is staged AWSCURRENT via GetSecretValue, so
"rotating" here just means: generate a new value, stage it, verify it's
readable, then promote it. Swap in real downstream calls in setSecret /
testSecret if you adapt this for a real credential.
"""
import boto3


def lambda_handler(event, context):
    secret_arn = event["SecretId"]
    token = event["ClientRequestToken"]
    step = event["Step"]

    client = boto3.client("secretsmanager")
    metadata = client.describe_secret(SecretId=secret_arn)
    if not metadata.get("RotationEnabled", False):
        raise ValueError(f"Secret {secret_arn} is not enabled for rotation")

    if step == "createSecret":
        create_secret(client, secret_arn, token)
    elif step == "setSecret":
        set_secret(client, secret_arn, token)
    elif step == "testSecret":
        test_secret(client, secret_arn, token)
    elif step == "finishSecret":
        finish_secret(client, secret_arn, token)
    else:
        raise ValueError(f"Unknown rotation step: {step}")


def create_secret(client, secret_arn, token):
    # Idempotent: if this token's AWSPENDING version already exists
    # (Lambda retried this step), do nothing further.
    try:
        client.get_secret_value(
            SecretId=secret_arn, VersionId=token, VersionStage="AWSPENDING"
        )
        return
    except client.exceptions.ResourceNotFoundException:
        pass

    new_value = client.get_random_password(ExcludePunctuation=True)["RandomPassword"]
    client.put_secret_value(
        SecretId=secret_arn,
        ClientRequestToken=token,
        SecretString=new_value,
        VersionStages=["AWSPENDING"],
    )


def set_secret(client, secret_arn, token):
    # No downstream system to push the new value to for this generic app
    # secret. A real DB-credential rotation would ALTER the DB user's
    # password here, using the AWSCURRENT credential to authenticate.
    return


def test_secret(client, secret_arn, token):
    # Confirm the AWSPENDING value is retrievable. A real integration
    # would use it to make an authenticated call to the downstream system
    # before finishSecret promotes it.
    client.get_secret_value(
        SecretId=secret_arn, VersionId=token, VersionStage="AWSPENDING"
    )


def finish_secret(client, secret_arn, token):
    metadata = client.describe_secret(SecretId=secret_arn)
    current_version = None
    for version_id, stages in metadata["VersionIdsToStages"].items():
        if "AWSCURRENT" in stages:
            if version_id == token:
                return  # already current -- nothing to do
            current_version = version_id
            break

    client.update_secret_version_stage(
        SecretId=secret_arn,
        VersionStage="AWSCURRENT",
        MoveToVersionId=token,
        RemoveFromVersionId=current_version,
    )
