clusters=msk,docker

msk.bootstrap.servers=<BootstrapBrokerStringSaslIam>
msk.security.protocol=SASL_SSL
msk.sasl.mechanism=AWS_MSK_IAM
msk.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
msk.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

docker.bootstrap.servers=localhost:29095
docker.security.protocol=SASL_PLAINTEXT
docker.sasl.mechanism=SCRAM-SHA-256
docker.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";

msk->docker.enabled=true
msk->docker.topics=orders
docker->msk.enabled=false

replication.factor=1
